# Generated by Django 4.1.5 on 2023-02-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalregistratedModels',
            fields=[
                ('register_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=50)),
                ('Date_Of_Birth', models.CharField(max_length=50)),
                ('Donate_Organ', models.CharField(max_length=50000)),
                ('Disease', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Hospital_registration',
            },
        ),
    ]
