# Generated by Django 4.1.5 on 2023-01-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationModels',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('father', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('photo', models.ImageField(null=True, upload_to='images/')),
                ('password', models.CharField(max_length=8, null=True)),
                ('gender', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'User_registration',
            },
        ),
    ]
