# Generated by Django 4.1.5 on 2023-01-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganapplicationModels',
            fields=[
                ('organ_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50, null=True)),
                ('Father', models.CharField(max_length=50, null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Phone', models.CharField(max_length=50, null=True)),
                ('City', models.CharField(max_length=50, null=True)),
                ('Disease', models.CharField(max_length=50, null=True)),
                ('Gender', models.CharField(max_length=50, null=True)),
                ('Date_Of_Birth', models.CharField(max_length=50, null=True)),
                ('Donate_Organ', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'Organ_application',
            },
        ),
    ]
