# Generated by Django 4.1.5 on 2023-02-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_organapplicationmodels_donate_organ'),
    ]

    operations = [
        migrations.AddField(
            model_name='organapplicationmodels',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
