# Generated by Django 4.1.5 on 2023-02-15 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_organapplicationmodels_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='organapplicationmodels',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
