# Generated by Django 4.1.5 on 2023-02-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_organapplicationmodels_datetime_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organapplicationmodels',
            name='datetime_created',
            field=models.DateField(null=True),
        ),
    ]
