# Generated by Django 4.1.5 on 2023-02-15 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_alter_organapplicationmodels_datetime_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organapplicationmodels',
            old_name='use',
            new_name='user',
        ),
    ]
