# Generated by Django 4.1.5 on 2023-02-15 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_rename_use_organapplicationmodels_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organapplicationmodels',
            old_name='user',
            new_name='use',
        ),
    ]
