# Generated by Django 4.1.5 on 2023-02-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_remove_organapplicationmodels_datetime_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organapplicationmodels',
            name='date',
        ),
        migrations.RemoveField(
            model_name='organapplicationmodels',
            name='description',
        ),
        migrations.RemoveField(
            model_name='organapplicationmodels',
            name='title',
        ),
        migrations.AddField(
            model_name='organapplicationmodels',
            name='datetime_created',
            field=models.DateField(null=True),
        ),
    ]
