# Generated by Django 4.1.5 on 2023-02-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_remove_organapplicationmodels_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organapplicationmodels',
            name='issued_status',
            field=models.CharField(default='Not issued', max_length=50),
        ),
        migrations.AlterField(
            model_name='organapplicationmodels',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
