# Generated by Django 4.1.5 on 2023-02-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_organapplicationmodels_issued_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organapplicationmodels',
            name='datetime_created',
        ),
        migrations.AddField(
            model_name='organapplicationmodels',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
