# Generated by Django 4.1.5 on 2023-02-16 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_remove_organapplicationmodels_datetime_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('overall', models.IntegerField(help_text='data', null=True)),
                ('travelling', models.IntegerField(help_text='travelling', null=True)),
                ('suggestion', models.CharField(help_text='suggestion', max_length=400, null=True)),
                ('sentiment', models.CharField(help_text='sentiment', max_length=80, null=True)),
                ('feedback2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.registrationmodels')),
            ],
            options={
                'db_table': 'UserFeedback_details',
            },
        ),
    ]
