# Generated by Django 4.1.5 on 2023-02-16 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0014_userfeedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFeedback',
            new_name='feedbackModels',
        ),
    ]
