# Generated by Django 4.1.5 on 2023-02-16 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0015_rename_userfeedback_feedbackmodels'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feedbackModels',
            new_name='feedbackM',
        ),
    ]
