# Generated by Django 4.1.5 on 2023-02-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0016_rename_feedbackmodels_feedbackm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackm',
            name='overall',
            field=models.IntegerField(help_text='overall', null=True),
        ),
    ]
