# Generated by Django 4.1.5 on 2023-02-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0017_alter_feedbackm_overall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackm',
            name='overall',
            field=models.IntegerField(help_text='data', null=True),
        ),
    ]
