# Generated by Django 4.1.5 on 2023-02-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0018_alter_feedbackm_overall'),
    ]

    operations = [
        migrations.AddField(
            model_name='organapplicationmodels',
            name='block1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organapplicationmodels',
            name='block2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organapplicationmodels',
            name='block3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organapplicationmodels',
            name='verification_status',
            field=models.CharField(default='pending', max_length=50, null=True),
        ),
    ]
